// This file is auto-generated by PacketGenerator.
using System;
using NetworkCore;

namespace Packet
{
    public enum PacketType : short
    {
        CreateRoomReq = 1001,
        CreateRoomRes = 1002,
        RoomListReq = 1003,
        RoomListRes = 1004,
    }

    public class CreateRoomReq
    {
        public string roomName { get; set; } = string.Empty;
    }

    public class CreateRoomRes
    {
        public byte result { get; set; }
        public uint roomId { get; set; }
    }

    public class RoomListReq
    {
    }

    public class RoomListRes
    {
        public List<string> roomList { get; set; } = new List<string>();
    }

    public static class PacketSerializer
    {
        public static byte[] Serialize(CreateRoomReq packet)
        {
            PacketWriter writer = new PacketWriter();
            writer.Write(packet.roomName);
            return writer.ToArray();
        }

        public static CreateRoomReq Deserialize_CreateRoomReq(byte[] data)
        {
            CreateRoomReq packet = new CreateRoomReq();
            PacketReader reader = new PacketReader(data);
            packet.roomName = reader.ReadString();;
            return packet;
        }
        public static byte[] Serialize(CreateRoomRes packet)
        {
            PacketWriter writer = new PacketWriter();
            writer.Write(packet.result);
            writer.Write(packet.roomId);
            return writer.ToArray();
        }

        public static CreateRoomRes Deserialize_CreateRoomRes(byte[] data)
        {
            CreateRoomRes packet = new CreateRoomRes();
            PacketReader reader = new PacketReader(data);
            packet.result = reader.ReadByte();;
            packet.roomId = reader.ReadUInt32();;
            return packet;
        }
        public static byte[] Serialize(RoomListReq packet)
        {
            PacketWriter writer = new PacketWriter();
            return writer.ToArray();
        }

        public static RoomListReq Deserialize_RoomListReq(byte[] data)
        {
            RoomListReq packet = new RoomListReq();
            PacketReader reader = new PacketReader(data);
            return packet;
        }
        public static byte[] Serialize(RoomListRes packet)
        {
            PacketWriter writer = new PacketWriter();
            writer.Write(packet.roomList);
            return writer.ToArray();
        }

        public static RoomListRes Deserialize_RoomListRes(byte[] data)
        {
            RoomListRes packet = new RoomListRes();
            PacketReader reader = new PacketReader(data);
            packet.roomList = reader.ReadStrings();;
            return packet;
        }
    }
}
