// This file is auto-generated by PacketGenerator.
using System;

namespace Packet
{
    public enum PacketType
    {
        CreateRoomReq = 1001,
        CreateRoomRes = 1002,
    }

    public class CreateRoomReq
    {
        public string roomName { get; set; }
    }

    public class CreateRoomRes
    {
        public byte result { get; set; }
        public uint roomNumber { get; set; }
    }

    public static class PacketSerializer
    {
        public static byte[] Serialize(CreateRoomReq packet)
        {
            PacketWriter writer = new PacketWriter();
            writer.Write(packet.roomName);
            return writer.ToArray();
        }

        public static CreateRoomReq Deserialize_CreateRoomReq(byte[] data)
        {
            CreateRoomReq packet = new CreateRoomReq();
            PacketReader reader = new PacketReader(data);
            packet.roomName = reader.ReadString();;
            return packet;
        }
        public static byte[] Serialize(CreateRoomRes packet)
        {
            PacketWriter writer = new PacketWriter();
            writer.Write(packet.result);
            writer.Write(packet.roomNumber);
            return writer.ToArray();
        }

        public static CreateRoomRes Deserialize_CreateRoomRes(byte[] data)
        {
            CreateRoomRes packet = new CreateRoomRes();
            PacketReader reader = new PacketReader(data);
            packet.result = reader.ReadByte();;
            packet.roomNumber = reader.ReadUInt32();;
            return packet;
        }
    }
}
